M48
; DRILL file {KiCad 7.0.9} date Tue Jan 30 02:49:18 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-30T02:49:18+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0374
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X4.4885Y-4.1762
X4.619Y-4.3626
T2
X5.0341Y-4.8275
X5.2332Y-4.9945
T3
X4.7006Y-1.9595
T0
M30
