M48
; DRILL file {KiCad 8.0.0} date 2024-03-25T03:31:54+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-25T03:31:54+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.5613Y-4.8659
X5.7811Y-4.807
T2
X5.3211Y-4.2266
M30
